### PR TITLE
Add D/Invoke support

### PR DESCRIPTION
**Pull request by S3cur3Th1sSh1t**
You can merge or otherwise use this to add D/Invoke on your own.

### CODE REVIEW

**Comment by GetRektBoy724** [comment]
thanks so much for adding a pull request!
I'm working on D/Invoke support on SharpUnhooker too!
I kinda worried if I use the D/Invoke code that included in this PR, it will make the code WAY WAY bigger, and I'm still working on some kind of "Tiny" D/Invoke. So my "Tiny" D/Invoke does not have the capability of loading a new DLL on the process, but for me, that's okay, cause probably `kernel32.dll` will be loaded on every single process on Windows.
And for now, I kinda more focused on adding the capability to unhook IAT hooks. So maybe for now, I'll hold this PR for a while.

**Comment by GetRektBoy724** [comment]
[DInvokeCore.txt](https://github.com/GetRektBoy724/SharpUnhooker/files/6603529/DInvokeCore.txt)
This is the code for "Tiny" D/Invoke that I mean

**Comment by S3cur3Th1sSh1t** [comment]
That’s fine for me. Take your time and stick on your own version. 👌 better for learning purposes.

**Comment by GetRektBoy724** [comment]
> That’s fine for me. Take your time and stick on your own version. ok_hand better for learning purposes.

:smile: :+1: 
oh and I'm (kinda) your "Fan" btw :wink:

**Comment by GetRektBoy724** [comment]
oh, I guess I don't need D/Invoke anymore lmao, cause SharpUnhooker only uses VirtualProtect API.
This is the list of the thing that I change from unmanaged API to .NET's managed API : 
- WriteProcessMemory : Marshal.Copy
- GetModuleHandle : System.Diagnostics.Process.Modules
- VirtualAlloc : Marshal.AllocHGlobal
- GetProcAddress : D/Invoke's GetExportAddress function

So because of that, I'm closing this PR, Sorry m8

**Comment by S3cur3Th1sSh1t** [comment]
VirtualProtect or especially NtProtectVirtualMemory is hooked by nearly all EDR vendors 😉

**Comment by GetRektBoy724** [comment]
> VirtualProtect or especially NtProtectVirtualMemory is hooked by nearly all EDR vendors

Oh shit really?
Thank god i already have working prototype code for D/Invoke implementation on SharpUnhooker.
Thanks so much for telling me out.I'll update the code ASAP :wink: 
Btw do you have Discord?

**Comment by S3cur3Th1sSh1t** [comment]
They all hook it. Just take a look here:

https://github.com/Mr-Un1k0d3r/EDRs

you can DM me on Twitter if you have questions about that ;-)

**Comment by GetRektBoy724** [comment]
> They all hook it. Just take a look here:
> 
> https://github.com/Mr-Un1k0d3r/EDRs
> 
> you can DM me on Twitter if you have questions about that ;-)

Oh ok, thx for the resource!
Well,I don't have Twitter :joy:

**Pull request closed without merging**
